jobs:
  - template: default.yml@templates
    parameters:
      cross: false
      minrust: 1.60.0
      setup:
        - script: sudo apt install libpam0g-dev

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/master
      endpoint: 1wilkens
