stages:
  - template: default.yml@templates
    parameters:
      cross: false
      setup:
        - script: sudo apt install libpam0g-dev

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: 1wilkens
